name: Deploy Astro site to GitHub Pages

on:
  push:
    branches: ["main"] # despliega en cada push a main
  pull_request:
    branches: ["main"] # opcional: corre build en PRs para probar

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Astro recomienda Node 18 o 20

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: withastro/action@v2
        with:
          path: ./dist # carpeta que genera Astro al hacer build
